import { Banner, Product } from "./api-services";
import { Category } from "@/types/category";

export const MOCK_CATEGORIES: Category[] = [
    { id: 1, name: "Electronics", slug: "electronics" },
    { id: 2, name: "Fashion", slug: "fashion" },
    { id: 3, name: "Home & Garden", slug: "home-garden" },
    { id: 4, name: "Sports", slug: "sports" },
];

export const MOCK_BANNERS: Banner[] = [
    {
        id: 0,
        title: "Mid Season Mega Sale",
        subtitle: "Limited-time offers across all categories",
        imageUrl: "https://images.unsplash.com/photo-1607082350899-7e105aa886ae?q=80&w=2070&auto=format&fit=crop",
        buttonText: "Shop Deals",
        buttonLink: "/products",
        isActive: true,
        order: 0,
        companyId: "COMP-000001",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 1,
        title: "Summer Collection 2026",
        subtitle: "Up to 50% off on all summer essentials",
        imageUrl: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?q=80&w=2070&auto=format&fit=crop",
        buttonText: "Shop Now",
        buttonLink: "/products",
        isActive: true,
        order: 1,
        companyId: "COMP-000001",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 2,
        title: "Gadget Galore",
        subtitle: "Latest smartphones and laptops at unbeatable prices",
        imageUrl: "https://images.unsplash.com/photo-1498049794561-7780e7231661?q=80&w=2070&auto=format&fit=crop",
        buttonText: "View Deals",
        buttonLink: "/products?category=electronics",
        isActive: true,
        order: 2,
        companyId: "COMP-000001",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: 1,
        name: "Premium Wireless Headphones",
        sku: "PH-001",
        price: 199.99,
        discountPrice: 149.99,
        description: "Experience crystal clear sound with our premium wireless headphones. Feature active noise cancellation and 40-hour battery life.",
        images: [{ url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop", isPrimary: true }],
        thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=400&auto=format&fit=crop",
        isActive: true,
        isFlashSell: true,
        flashSellPrice: 129.99,
        category: MOCK_CATEGORIES[0],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: "Classic Leather Watch",
        sku: "CW-002",
        price: 120.00,
        description: "A timeless classic. Genuine leather strap with a minimalist stainless steel dial.",
        images: [{ url: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=2000&auto=format&fit=crop", isPrimary: true }],
        thumbnail: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=400&auto=format&fit=crop",
        isActive: true,
        isFlashSell: false,
        category: MOCK_CATEGORIES[1],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: "Nordic Ceramic Vase",
        sku: "NV-003",
        price: 45.00,
        discountPrice: 35.00,
        description: "Elegant ceramic vase inspired by Scandinavian design. Perfect for any modern home.",
        images: [{ url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?q=80&w=1974&auto=format&fit=crop", isPrimary: true }],
        thumbnail: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?q=80&w=400&auto=format&fit=crop",
        isActive: true,
        isFlashSell: false,
        category: MOCK_CATEGORIES[2],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: "Ergonomic Running Shoes",
        sku: "RS-004",
        price: 89.99,
        description: "Engineered for performance and comfort. Lightweight and breathable material.",
        images: [{ url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop", isPrimary: true }],
        thumbnail: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=400&auto=format&fit=crop",
        isActive: true,
        isFlashSell: true,
        flashSellPrice: 69.99,
        category: MOCK_CATEGORIES[3],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
